---
keyvault_state: "present"
az_kv_debug: false

keyvault:
  secrets:
    resource_group_key: aks_re1
    vault_name: copsvault
    location_key: region1
    enable_soft_delete: no
    enabled_for_deployment : no
    enabled_for_disk_encryption : no
    enabled_for_template_deployment: no
    recover_mode: no
    sku:
      name: standard
    access_policies:
      - object_id: "8a66242a-4890-4cc3-9f5e-6b0737ba3b90"
        secrets:
          - set
          - get
          - list
          - delete
          - purge
          - recover
        certificates:
          - create
          - get
          - list
          - delete
          - purge
          - recover
#      - object_id: ingress
#        secrets:
#          - get
#        certificates:
#          - get
#      - object_id: apgw_keyvault_secrets
#        secrets:
#          - get
#        certificates:
#          - get
