---
vnet_state: "present"
peering_state: "present"
subnet_state: "present"

virtualnetwork:
  hub:
    resource_group_key: rg_ntw_hub_we_001
    location_key: region1
    name: vnet_ntw_hub_we_001
    state: present
    purge_dns_servers: no
    purge_address_prefixes: no
    append_tags: yes
    address_prefix_cidr:
      - "10.1.0.0/16"
    tags:
      env: dev
  spoke_dev:
    resource_group_key: rg_ntw_dev_we_001
    location_key: region1
    name: vnet_ntw_dev_we_001
    state: present
    purge_dns_servers: no
    purge_address_prefixes: no
    append_tags: yes
    address_prefix_cidr:
      - "10.0.0.0/16"
    tags:
      env: dev

virtualnetworkpeering:
  vnetp_dev_to_hub:
    name: vnetp_dev_to_hub
    state: present
    allow_forwarded_traffic: no
    allow_gateway_transit: no
    allow_virtual_network_access: yes
    virtual_network_key: spoke_dev
    remote_virtual_network_key: hub
    use_remote_gateways: no
  vnetp_hub_to_dev:
    name: vnetp_hub_to_dev
    state: present
    allow_forwarded_traffic: yes
    allow_gateway_transit: yes
    allow_virtual_network_access: yes
    virtual_network_key: hub
    remote_virtual_network_key: spoke_dev
    use_remote_gateways: no

subnet:
  AzureBastionSubnetHub:
    virtual_network_name_key: hub
    name: AzureBastionSubnet
    address_prefix_cidr: "10.1.1.0/24"
    security_group_key: "azure_bastion_nsg"
  GatewaySubnetHub:
    virtual_network_name_key: hub
    name: GatewaySubnet
    address_prefix_cidr: "10.1.2.0/24"
  vnets_app_001:
    virtual_network_name_key: spoke_dev
    name: vnets_app_001
    address_prefix_cidr: "10.0.8.0/21"
    security_group_key: "app_nsg"
