---
subnet_state: "present"

subnet:
  AzureBastionSubnetHub:
    virtual_network_name_key: hub
    name: AzureBastionSubnet
    address_prefix_cidr: "10.1.1.0/24"
    security_group_key: "azure_bastion_nsg"
  GatewaySubnetHub:
    virtual_network_name_key: hub
    name: GatewaySubnet
    address_prefix_cidr: "10.1.2.0/24"
  vnets_app_001:
    virtual_network_name_key: spoke_dev
    name: vnets_app_001
    address_prefix_cidr: "10.0.8.0/21"
    security_group_key: "app_nsg"
