---
keyvault_state: "present"
az_kv_debug: false

keyvault:
  secrets:
    resource_group_key: rg_ntw_dev_we_001
    vault_name: kvntwdevwe001
    location_key: region1
    enable_soft_delete: no
    enabled_for_deployment : yes
    enabled_for_disk_encryption : yes
    enabled_for_template_deployment: yes
    recover_mode: no
    # Add some default secrets to keyvault
    keyvaultsecret:
      - secret_name: admin-dev-password
        secret_value: "{{ lookup('password', '/dev/null', seed=inventory_hostname) }}"
    sku:
      name: standard
    access_policies:
      - object_id: "8a66242a-4890-4cc3-9f5e-6b0737ba3b90"
        secrets:
          - set
          - get
          - list
          - delete
          - purge
          - recover
        certificates:
          - create
          - get
          - list
          - delete
          - purge
          - recover
