---
securitygroup_state: "present"

securitygroup:
  app_nsg:
    name: nsg_ntw_dev_we_app_001
    rules: []
  azure_bastion_nsg:
    name: nsg_ntw_dev_we_bh_001
    rules:
      - name: in-allow-https
        priority: 120
        direction: Inbound
        access: Allow
        protocol: Tcp
        source_port_range: '*'
        destination_port_range: 443
        source_address_prefix: Internet
        destination_address_prefix: '*'
      - name: in-allow-gateway-manager
        priority: 130
        direction: Inbound
        access: Allow
        protocol: Tcp
        source_port_range: '*'
        destination_port_range: 443
        source_address_prefix: GatewayManager
        destination_address_prefix: '*'
      - name: in-allow-load-balancer
        priority: 140
        direction: Inbound
        access: Allow
        protocol: Tcp
        source_port_range: '*'
        destination_port_range: 443
        source_address_prefix: AzureLoadBalancer
        destination_address_prefix: '*'
      - name: in-allow-bastion-host-communication-8080
        priority: 150
        direction: Inbound
        access: Allow
        protocol: '*'
        source_port_range: '*'
        destination_port_range: 8080
        source_address_prefix: VirtualNetwork
        destination_address_prefix: VirtualNetwork
      - name: out-vnet-allow-22
        priority: 100
        direction: Outbound
        access: Allow
        protocol: '*'
        source_port_range: '*'
        destination_port_range: 22
        source_address_prefix: '*'
        destination_address_prefix: VirtualNetwork
      - name: out-vnet-allow-3389
        priority: 101
        direction: Outbound
        access: Allow
        protocol: '*'
        source_port_range: '*'
        destination_port_range: 3389
        source_address_prefix: '*'
        destination_address_prefix: VirtualNetwork
      - name: out-azure-cloud-allow-3389
        priority: 110
        direction: Outbound
        access: Allow
        protocol: Tcp
        source_port_range: '*'
        destination_port_range: 443
        source_address_prefix: '*'
        destination_address_prefix: AzureCloud
      - name: out-communication-allow-8080
        priority: 120
        direction: Outbound
        access: Allow
        protocol: Tcp
        source_port_range: '*'
        destination_port_range: 8080
        source_address_prefix: VirtualNetwork
        destination_address_prefix: VirtualNetwork
      - name: out-gateway-information-allow
        priority: 130
        direction: Outbound
        access: Allow
        protocol: '*'
        source_port_range: '*'
        destination_port_range: 80
        source_address_prefix: '*'
        destination_address_prefix: Internet
