---
#
# Get prerequisites
#

# Public IP ID
- name: Get facts For Bastion Public IP
  azure_rm_publicipaddress_info:
    resource_group: "{{ resourcegroup[ bastions.hub.resource_group_key ].name }}"
    name: "{{ bastions.hub.public_ip_name }}"
  register: public_ip_var
  tags: bastion
  when: bastion_state == "present"

- debug: 
    var: public_ip_var.publicipaddresses[0].id
  tags: bastion
  when: bastion_state == "present"

# Subnet ID
- name: Get facts For Bastion Subnet
  azure_rm_subnet_info:
    resource_group: "{{ resourcegroup[ bastions.hub.resource_group_key ].name }}"
    virtual_network_name: "{{ virtualnetwork[ subnet[ bastions.hub.subnet_key ].virtual_network_name_key ].name }}"
    name: "{{ subnet[ bastions.hub.subnet_key ].name }}"
  register: subnet_var
  tags: bastion
  when: bastion_state == "present"

- debug: 
    var: subnet_var.subnets[0].id
  tags: bastion
  when: bastion_state == "present"

- name: Check mandatory variables are defined
  assert:
    that:
      - public_ip_var.publicipaddresses[0].id is defined
      - subnet_var.subnets[0].id is defined
  tags: bastion
  when: bastion_state == "present"

#
# Bastion host API call
# REST API: https://docs.microsoft.com/en-us/rest/api/virtualnetwork/bastion-hosts/create-or-update#subresource
- name: Bastion Host Action [{{ bastion_state }}]
  azure_rm_resource:
    api_version: "{{ bastion_resource_api.api_version }}"
    method: "{% if bastion_state==\"present\" %}PUT{% else %}DELETE{% endif %}"
    resource_group: "{{ resourcegroup[ bastions.hub.resource_group_key ].name }}"
    provider: "{{ bastion_resource_api.provider }}"
    resource_type: "{{ bastion_resource_api.resource_type }}"
    resource_name: "{{ bastions.hub.resource_name }}"
    body:
      location: "{{ global_settings.locations[ bastions.hub.location_key | default(global_settings.default_region) ] }}"
      sku:
        name: "{{ bastions.hub.sku }}"
      properties:
        scaleUnits: "{{ bastions.hub.scaleUnits }}"
        ipConfigurations:
          - name: "{{ bastions.hub.public_ip_name }}"
            properties: 
              publicIPAddress: 
                id: "{{ public_ip_var.publicipaddresses[0].id | default(\"none\") }}"
              subnet:
                id: "{{ subnet_var.subnets[0].id | default(\"none\") }}"
  tags: bastion



#- debug: 
#    var: bastion_info
#  tags: bastion