---
- name: Log Analytics Action [{{ loganalytics_state }}]
  azure_rm_loganalyticsworkspace:
    resource_group: "{{ resourcegroup[ item.value.resource_group_key ].name }}"
    name: "{{ item.value.name }}"
    retention_in_days: "{{ item.value.retention_in_days }}"
    intelligence_packs: "{{ item.value.intelligence_packs | default({}) }}"
    sku: "{{ item.value.sku }}"
    force: "{{ loganalytics_force | default(no) }}"
    state: "{{ loganalytics_state | default('present') }}"
  with_dict: "{{ loganalyticsworkspace }}"
  register: loganalyticsworkspace_res
#- debug: 
#    var: loganalyticsworkspace_res
#  when:
#    az_debug is defined and az_debug == true
#
#- debug: 
#    var: loganalyticsworkspace_res.results[0].id

- name: insert a line at the beginning of the file, and back it up
  lineinfile: 
    dest: "{{ role_path }}/vars/main/log_analytics.runtime.yml"
    state: present 
    line: "workspaceId: {{ loganalyticsworkspace_res.results[0].id }}" 
    insertbefore: "BOF" 
    backup: no
    create: yes