---
- name: Create Resource Groups
  include_tasks:
    file: task.resourcegroup.yml
  vars:
    resourcegroup_vars: "{{ item.value }}"
    resourcegroup_state: present
  with_dict: "{{ resourcegroup }}"
  tags:
    - resourcegroup

- name: Create LogAnalytics Workspace
  include_tasks:
    file: task.loganalyticsworkspace.yml
  vars:
    loganalyticsworkspace_vars: "{{ item.value }}"
    loganalyticsworkspace_state: present
  with_dict: "{{ loganalyticsworkspace }}"
  tags:
    - loganalyticsworkspace

- name: Create Virtual Network
  include_tasks:
    file: task.virtualnetwork.yml
  vars:
    virtualnetwork_vars: "{{ item.value }}"
    virtualnetwork_state: present
  with_dict: "{{ virtualnetwork }}"
  tags:
    - virtualnetwork

- name: Create Virtual Network Peering
  include_tasks:
    file: task.virtualnetworkpeering.yml
  vars:
    virtualnetworkpeering_vars: "{{ item.value }}"
    virtualnetworkpeering_state: present
  with_dict: "{{ virtualnetworkpeering }}"
  tags:
    - virtualnetworkpeering

- name: Create Subnets
  include_tasks:
    file: task.subnet.yml
  vars:
    subnet_vars: "{{ item.value }}"
    subnet_state: present
  with_dict: "{{ subnet }}"
  tags:
    - subnet

- name: Create KeyVault
  include_tasks:
    file: task.keyvault.yml
  vars:
    keyvault_vars: "{{ keyvault.secrets }}"
    keyvault_state: present
  tags:
    - keyvault

- name: Create KeyVault Secrets
  include_tasks:
    file: task.keyvaultsecret.yml
  vars:
    keyvaultsecret_vars: "{{ item }}"
    keyvaultsecret_vault_name: "{{ keyvault.secrets.vault_name }}"
    keyvaultsecret_state: present
  loop: "{{ keyvault.secrets.keyvaultsecret }}"
  tags:
    - keyvaultsecret

- name: Create Public IP For Bastion Host
  include_tasks:
    file: task.publicipaddress.yml
  vars:
    publicipaddress_vars: "{{ bastions.hub }}"
    publicipaddress_state: present
  tags:
    - publicipaddress

- name: Create Bastion Host
  include_tasks:
    file: task.bastionhosts.yml
  vars:
    bastionhosts_vars: "{{ bastions.hub }}"
    bastionhosts_state: present
  tags:
    - bastionhosts

- name: Wait For Bastion Host To Be Deleted
  include_tasks:
    file: task.wait.yml
  vars:
    wait_vars: "{{ bastions.hub }}"
    wait_status: "Succeeded"
    wait_delay: "{{ bastions.hub.timers.delete.delay }}"
    wait_retries: "{{ bastions.hub.timers.delete.retries }}"
  tags:
    - wait

#- name: Create Public IP For Bastion Host
#  include_tasks:
#    file: task.publicipaddress.yml
#  vars:
#    publicipaddress_vars: "{{ bastions.hub }}"
#    publicipaddress_state: absent
#  tags:
#    - publicipaddress

- name: Create Virtual Machine
  include_tasks:
    file: task.virtualmachine.yml
  vars:
    virtualmachine_vars: "{{ virtualmachine.sandbox }}"
    virtualmachine_state: present
  tags:
    - virtualmachine

- name: Create Network Interfaces
  include_tasks:
    file: task.networkinterface.yml
  vars:
    networkinterface_vars: "{{ networkinterfaces.nic1 }}"
    networkinterface_state: absent
  tags:
    - networkinterface