---
- name: Print NSG variables
  debug:
    msg: |
      --------------------------------
      NSG Key:              {{ item.value['security_group_key'] }}
      NSG Name:             {{ securitygroup[ item.value['security_group_key'] ].name }}
      NSG RG:               {{ resourcegroup[ virtualnetwork[ item.value.virtual_network_name_key ].resource_group_key ].name }}
      NSG Rules:            {{ securitygroup[ item.value['security_group_key'] ]['rules']  }}
      ================================
  when: item.value['security_group_key'] is defined
  with_dict: "{{ subnet }}"

- name: NSG Action [{{ nsg_state }}]
  azure_rm_securitygroup: 
    resource_group: "{{ resourcegroup[ virtualnetwork[ item.value.virtual_network_name_key ].resource_group_key ].name }}"
    name: "{{ securitygroup[ item.value['security_group_key'] ].name  }}"
    rules: "{{ securitygroup[ item.value['security_group_key'] ]['rules']  }}"
    state: "{{ nsg_state | default('present') }}"
  when: item.value['security_group_key'] is defined
  with_dict: "{{ subnet }}"

- name: Print NSG variables
  debug:
    msg: |
      --------------------------------
      Subnet Name:            {{ item.value.name  }}
      Subnet CIDR:            {{ item.value.address_prefix_cidr }}
      Subnet VNET:            {{ item.value.virtual_network_name_key }}
      Subnet VNET Name:       {{ virtualnetwork[ item.value.virtual_network_name_key ].name }}
      Subnet RG Key:          {{ virtualnetwork[ item.value.virtual_network_name_key ].resource_group_key }}
      Subnet RG Name:         {{ resourcegroup[ virtualnetwork[ item.value.virtual_network_name_key ].resource_group_key ].name }}
      ================================
  with_dict: "{{ subnet }}"

- name: Subnet Action [{{ subnet_state }}]
  azure_rm_subnet:
    resource_group: "{{ resourcegroup[ virtualnetwork[ item.value.virtual_network_name_key ].resource_group_key ].name }}"
    virtual_network_name: "{{ virtualnetwork[ item.value.virtual_network_name_key ].name }}"
    name: "{{ item.value.name }}"
    address_prefix_cidr: "{{ item.value.address_prefix_cidr }}"
    security_group: "{{ securitygroup[ item.value['security_group_key'] | default() ].name  | default() }}"
    state: "{{ subnet_state | default('present') }}"
  with_dict: "{{ subnet }}"
