---
- name: KeyVault Secret Block
  block:
    - name: KeyVault Secret Block
      block:
        - name: Create a secret
          azure_rm_keyvaultsecret:
            secret_name: "{{ item.secret_name }}"
            secret_value: "{{ item.secret_value }}"
            keyvault_uri: "https://{{ keyvaultsecret_vault_name }}.vault.azure.net"
            state: "{{ keyvaultsecret_state }}"
  tags:
    - keyvaultsecret