---
- name: Print VNET variables
  debug:
    msg: |
      --------------------------------
      VNET Key:             {{ item.key }}
      RG Key:               {{ item.value.resource_group_key }}
      RG Name:              {{ resourcegroup[ item.value.resource_group_key ].name }}
      VNET address space:   {{ item.value.address_prefix_cidr }}
      VNET Name:            {{ item.value.name }}
      ================================
  with_dict: "{{ virtualnetwork }}"


- name: Virtual Network Action [{{ vnet_state }}]
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup[ item.value.resource_group_key ].name }}"
    name: "{{ item.value.name }}"
    address_prefixes_cidr: "{{ item.value.address_prefix_cidr }}"
    dns_servers: "{{ item.value.dns_servers | default([]) }}"
    tags: "{{ item.value.tags | default({}) }}"
    state: "{{ vnet_state | default('present') }}"
  with_dict: "{{ virtualnetwork }}"

- name: Print VNET peering variables
  debug:
    msg: |
      --------------------------------
      Peering Key:          {{ item.key }}
      Peering Name:         {{ item.value.name }}
      VNET "From" Key:      {{ item.value.virtual_network_key }}
      VNET "From" Name:     {{ virtualnetwork[ item.value.virtual_network_key ].name }}
      VNET "To" Key:        {{ item.value.remote_virtual_network_key }}
      VNET "To" Name:       {{ virtualnetwork[ item.value.remote_virtual_network_key ].name  }}
      RG "From" Key:        {{ virtualnetwork[ item.value.virtual_network_key ].resource_group_key  }}
      RG "From" Name:       {{ resourcegroup[ virtualnetwork[ item.value.virtual_network_key ].resource_group_key ].name }}
      RG "To" Key:          {{ virtualnetwork[ item.value.remote_virtual_network_key ].resource_group_key }}
      RG "To" Name:         {{ resourcegroup[ virtualnetwork[ item.value.remote_virtual_network_key ].resource_group_key ].name }}
      ================================
  with_dict: "{{ virtualnetworkpeering }}"

- name: Virtual Network Peering Action [{{ peering_state }}]
  azure_rm_virtualnetworkpeering:
    resource_group: "{{ resourcegroup[ virtualnetwork[ item.value.virtual_network_key ].resource_group_key ].name }}"
    virtual_network: "{{ virtualnetwork[ item.value.virtual_network_key ].name }}"
    name: "{{ item.value.name }}"
    remote_virtual_network:
      resource_group: "{{ resourcegroup[ virtualnetwork[ item.value.remote_virtual_network_key ].resource_group_key ].name }}"
      name: "{{ virtualnetwork[ item.value.remote_virtual_network_key ].name }}"
    allow_virtual_network_access: "{{ item.value.allow_virtual_network_access | default(no) }}"
    allow_forwarded_traffic: "{{ item.value.allow_forwarded_traffic | default(no) }}"
    allow_gateway_transit: "{{ item.value.allow_gateway_transit | default(no) }}"
    use_remote_gateways: "{{ item.value.use_remote_gateways | default(no) }}"
    state: "{{ peering_state | default('present') }}"
  when: vnet_state == "present"
  with_dict: "{{ virtualnetworkpeering }}"
